#!/bin/bash

#SBATCH --gres=gpu:1
#SBATCH --job-name=TransformData
#SBATCH --ntasks=1
#SBATCH --partition=gpu_titanrtx_shared_course
#SBATCH --cpus-per-task=3
#SBATCH --time=00:30:00
#SBATCH --mem=32000M
#SBATCH --output=jobs/job_logs/transform_data_%A.out

module purge
module load 2021
module load Anaconda3/2021.05

cd $HOME/othello-gpt-probing/
source activate othello

python data/transform_data.py